import type { CaseRecord } from "./types";

export const SAMPLE_CASES: CaseRecord[] = [
  {
    case_id: "LEX-2026-0881",
    mandate_hash: "0x3f7a918b95c328e1d55681cbda93cbb4df7a19543beadfa3513a96cbfa148721",
    delivery_hash: "0x89dca12b509ef8544e45c73bc796918817a2dcfeea860b73c9f286ea2ba19e83",
    policy: "SOFTWARE_WEB_V1",
    status: "FINALIZED",
    created_at: "2026-09-08T14:22:10Z",
    updated_at: "2026-09-08T14:23:45Z",
    judgment_hash: "0x55cae4971c2217c917b4c6e9a0364d9f7e71c99837a28beea98dfa276189e31a",
    report_hash: "0x77c29be190ca8817bca458df9037cba816d991bce768ba2f99acff298288119b",
    judgment: {
      schemaVersion: "1.0",
      caseId: "LEX-2026-0881",
      verdict: "FULFILLED",
      confidenceBps: 9800,
      settlementBps: 10000,
      summary: "All mandatory criteria satisfied. The public API responds with HTTP 200 over TLS 1.3, JSON schema validation passed with zero field errors, and SHA-256 binary hash matched the committed deployment digest.",
      criteria: [
        {
          id: "crit-api-live",
          weightBps: 4000,
          critical: true,
          description: "Production API endpoint responds with HTTP 200 OK within 500ms latency",
          result: "PASS",
          severity: "CRITICAL",
          evidenceRefs: ["ev-endpoint-ping"],
          reasonCode: "STATUS_OK",
          reason: "Endpoint https://api.agentic.network/v1/health returned 200 OK, latency 82ms, TLS certificate verified.",
        },
        {
          id: "crit-schema-match",
          weightBps: 3000,
          critical: true,
          description: "Payload strictly conforms to OpenAPI 3.1 schema specification",
          result: "PASS",
          severity: "HIGH",
          evidenceRefs: ["ev-json-payload"],
          reasonCode: "SCHEMA_VALID",
          reason: "All 18 required attributes present with exact types. Zero undeclared fields detected.",
        },
        {
          id: "crit-unit-tests",
          weightBps: 3000,
          critical: false,
          description: "100% test coverage report published to public repository commit",
          result: "PASS",
          severity: "MEDIUM",
          evidenceRefs: ["ev-test-coverage"],
          reasonCode: "COVERAGE_MET",
          reason: "CI test suite passed 48 of 48 test assertions with 98.4% line coverage.",
        },
      ],
      admissibility: [
        {
          id: "ev-endpoint-ping",
          status: "ADMISSIBLE",
          reason: "Live HTTPS query performed by GenLayer validator consensus. Observed response body matched.",
        },
        {
          id: "ev-json-payload",
          status: "ADMISSIBLE",
          reason: "Content retrieved directly from public HTTPS endpoint. SHA-256 integrity verified.",
        },
        {
          id: "ev-test-coverage",
          status: "ADMISSIBLE",
          reason: "Committed git commit digest verified against repository release snapshot.",
        },
      ],
      contradictions: [],
      materialBreaches: [],
      missingEvidence: [],
      appealGrounds: [],
    },
  },
  {
    case_id: "LEX-2026-0882",
    mandate_hash: "0x12cba98319f0715e443890bb8ca179b5d2e4857b613acfe85698b7cb891544a0",
    delivery_hash: "0x77ae6152bc47816bbd924ca5508824ef627a154881bc3341ea227fa512689aa9",
    policy: "RESEARCH_DATA_V1",
    status: "FINALIZED",
    created_at: "2026-09-09T09:10:00Z",
    updated_at: "2026-09-09T09:12:15Z",
    judgment_hash: "0x98cfb1259a726ea892548cc0b17822fe8629ba5182cca35189ebbb51401341e9",
    report_hash: "0x44fa71bb5582312984ea0bc7754611ad501724bb92361acbb00912cca145b238",
    judgment: {
      schemaVersion: "1.0",
      caseId: "LEX-2026-0882",
      verdict: "PARTIALLY_FULFILLED",
      confidenceBps: 9200,
      settlementBps: 6500,
      summary: "Primary dataset delivered with correct schema and 10,000 observations. However, secondary citation corroboration was incomplete for 2 out of 10 sampled sources.",
      criteria: [
        {
          id: "crit-data-volume",
          weightBps: 5000,
          critical: true,
          description: "Dataset contains minimum 10,000 structured research rows",
          result: "PASS",
          severity: "CRITICAL",
          evidenceRefs: ["ev-dataset-s3"],
          reasonCode: "VOLUME_MET",
          reason: "Parsed CSV rows count exactly 10,420 valid observations.",
        },
        {
          id: "crit-cross-citations",
          weightBps: 3000,
          critical: false,
          description: "Every cited claim corroborates with independent DOI or government data feed",
          result: "PARTIAL",
          severity: "MEDIUM",
          evidenceRefs: ["ev-doi-records"],
          reasonCode: "PARTIAL_CITATIONS",
          reason: "8 out of 10 sampled DOIs verified; 2 links returned HTTP 404 or domain placeholder.",
        },
        {
          id: "crit-reproducibility-script",
          weightBps: 2000,
          critical: false,
          description: "Python data extraction script runs deterministically with specified seed",
          result: "FAIL",
          severity: "LOW",
          evidenceRefs: ["ev-py-script"],
          reasonCode: "EXECUTION_ERROR",
          reason: "Script encountered missing dependency 'pandas-datareader' not pinned in environment.",
        },
      ],
      admissibility: [
        {
          id: "ev-dataset-s3",
          status: "ADMISSIBLE",
          reason: "HTTPS download succeeded and SHA-256 matches submitted commitment hash.",
        },
        {
          id: "ev-doi-records",
          status: "ADMISSIBLE",
          reason: "Public DOI resolver accessed; 2 references unverifiable due to upstream dead links.",
        },
        {
          id: "ev-py-script",
          status: "ADMISSIBLE",
          reason: "Source code file inspected directly from committed artifact bundle.",
        },
      ],
      contradictions: ["Provider claimed 100% citation reliability in manifest summary, but 2 sources failed."],
      materialBreaches: [],
      missingEvidence: ["Working dependency lockfile for extraction script"],
      appealGrounds: ["Provider may resubmit corrected environment lockfile under secondary dispute window."],
    },
  },
  {
    case_id: "LEX-2026-0883",
    mandate_hash: "0x88fca992817bc1645e9921bb8817ba35dc224857b613acfe85698b7cb89199a1",
    delivery_hash: "0x22be6152bc47816bbd924ca5508824ef627a154881bc3341ea227fa5126811e2",
    policy: "GENERAL_V1",
    status: "FINALIZED",
    created_at: "2026-09-09T18:40:00Z",
    updated_at: "2026-09-09T18:41:50Z",
    judgment_hash: "0x66cfb1259a726ea892548cc0b17822fe8629ba5182cca35189ebbb51401399f4",
    report_hash: "0x11fa71bb5582312984ea0bc7754611ad501724bb92361acbb00912cca145a331",
    judgment: {
      schemaVersion: "1.0",
      caseId: "LEX-2026-0883",
      verdict: "BREACHED",
      confidenceBps: 9900,
      settlementBps: 0,
      summary: "Critical acceptance criterion failed. The delivered smart contract address was unverified on the specified blockchain explorer and binary bytecode differed from committed git source.",
      criteria: [
        {
          id: "crit-contract-deploy",
          weightBps: 6000,
          critical: true,
          description: "Smart contract deployed to Base Sepolia matching git repository commit hash",
          result: "FAIL",
          severity: "CRITICAL",
          evidenceRefs: ["ev-explorer-url"],
          reasonCode: "BYTECODE_MISMATCH",
          reason: "Deployed bytecode at target address does not match compiled output of committed repository.",
        },
        {
          id: "crit-security-audit",
          weightBps: 4000,
          critical: true,
          description: "Third-party audit report confirming zero critical or high vulnerabilities",
          result: "UNVERIFIABLE",
          severity: "HIGH",
          evidenceRefs: ["ev-audit-pdf"],
          reasonCode: "INVALID_SIGNATURE",
          reason: "Audit report PDF hash does not match auditor PGP release key.",
        },
      ],
      admissibility: [
        {
          id: "ev-explorer-url",
          status: "ADMISSIBLE",
          reason: "Explorer API queried; address verified as existing contract but bytecode failed match.",
        },
        {
          id: "ev-audit-pdf",
          status: "INADMISSIBLE",
          reason: "Cryptographic signature validation failed.",
        },
      ],
      contradictions: ["Manifest claimed audited deployment, but audit report signature was forged."],
      materialBreaches: ["Failure of critical deployment criterion", "Inadmissible forged audit certification"],
      missingEvidence: ["Valid signed auditor report"],
      appealGrounds: [],
    },
  },
];
